//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách sạn khả dụng.
        /// </summary>
        public static string BookingAvailableHotel {
            get {
                return ResourceManager.GetString("BookingAvailableHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string BookingDayText {
            get {
                return ResourceManager.GetString("BookingDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ từ.
        /// </summary>
        public static string BookingFromText {
            get {
                return ResourceManager.GetString("BookingFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đêm.
        /// </summary>
        public static string BookingNightText {
            get {
                return ResourceManager.GetString("BookingNightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tăng dần.
        /// </summary>
        public static string BookingPriceAsc {
            get {
                return ResourceManager.GetString("BookingPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá giảm dần.
        /// </summary>
        public static string BookingPriceDesc {
            get {
                return ResourceManager.GetString("BookingPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phạm vi giá.
        /// </summary>
        public static string BookingPriceRangeText {
            get {
                return ResourceManager.GetString("BookingPriceRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại.
        /// </summary>
        public static string BookingResetText {
            get {
                return ResourceManager.GetString("BookingResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn phòng.
        /// </summary>
        public static string BookingSelectRoomText {
            get {
                return ResourceManager.GetString("BookingSelectRoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string BookingSortText {
            get {
                return ResourceManager.GetString("BookingSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bản đồ.
        /// </summary>
        public static string BookingViewMap {
            get {
                return ResourceManager.GetString("BookingViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỀ TÊN CÔNG TY CHÚNG TÔI.
        /// </summary>
        public static string FooterMenuAboutOurCompanyTitle {
            get {
                return ResourceManager.GetString("FooterMenuAboutOurCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về chúng tôi.
        /// </summary>
        public static string FooterMenuAboutUs {
            get {
                return ResourceManager.GetString("FooterMenuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾT NỐI VỚI CHÚNG TÔI.
        /// </summary>
        public static string FooterMenuConnectUsTitle {
            get {
                return ResourceManager.GetString("FooterMenuConnectUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sở hữu độc quyền của.
        /// </summary>
        public static string FooterMenuCopyRightText {
            get {
                return ResourceManager.GetString("FooterMenuCopyRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TẢI ỨNG DỤNG.
        /// </summary>
        public static string FooterMenuDownloadAppTitle {
            get {
                return ResourceManager.GetString("FooterMenuDownloadAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CHÍNH SÁCH.
        /// </summary>
        public static string FooterMenuPolicyInfo {
            get {
                return ResourceManager.GetString("FooterMenuPolicyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách đổi, trả và hoàn tiền.
        /// </summary>
        public static string FooterMenuPolicyInfoExchangePolicy {
            get {
                return ResourceManager.GetString("FooterMenuPolicyInfoExchangePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo mật.
        /// </summary>
        public static string FooterMenuPolicyInfoPrivacyPolicy {
            get {
                return ResourceManager.GetString("FooterMenuPolicyInfoPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách giao nhận phòng.
        /// </summary>
        public static string FooterMenuPolicyInfoRoomDeliveryPolicy {
            get {
                return ResourceManager.GetString("FooterMenuPolicyInfoRoomDeliveryPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Toàn bộ.
        /// </summary>
        public static string HomeBlogTextSeeAll {
            get {
                return ResourceManager.GetString("HomeBlogTextSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string HomeBlogTitle {
            get {
                return ResourceManager.GetString("HomeBlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá ngay.
        /// </summary>
        public static string HomeExplore {
            get {
                return ResourceManager.GetString("HomeExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khách sạn.
        /// </summary>
        public static string HomeListHotelTitle {
            get {
                return ResourceManager.GetString("HomeListHotelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình khuyến mãi.
        /// </summary>
        public static string HomePromotionProgramTitle {
            get {
                return ResourceManager.GetString("HomePromotionProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm hiểu thêm .
        /// </summary>
        public static string HomePromotionTextLearnMore {
            get {
                return ResourceManager.GetString("HomePromotionTextLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm phòng.
        /// </summary>
        public static string HomeSearch {
            get {
                return ResourceManager.GetString("HomeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vị trí.
        /// </summary>
        public static string HomeSelectLocation {
            get {
                return ResourceManager.GetString("HomeSelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tỉnh / Thành phố.
        /// </summary>
        public static string HomeSelectLocationPlaceholder {
            get {
                return ResourceManager.GetString("HomeSelectLocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXem thêm.
        /// </summary>
        public static string HomeTextSeeMore {
            get {
                return ResourceManager.GetString("HomeTextSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về chúng tôi .
        /// </summary>
        public static string MenuAboutUs {
            get {
                return ResourceManager.GetString("MenuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt phòng.
        /// </summary>
        public static string MenuBooking {
            get {
                return ResourceManager.GetString("MenuBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lớn.
        /// </summary>
        public static string SearchAmountAdultTitle {
            get {
                return ResourceManager.GetString("SearchAmountAdultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trẻ em.
        /// </summary>
        public static string SearchAmountChildTitle {
            get {
                return ResourceManager.GetString("SearchAmountChildTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng.
        /// </summary>
        public static string SearchAmountRoomTitle {
            get {
                return ResourceManager.GetString("SearchAmountRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string SearchAmountTitle {
            get {
                return ResourceManager.GetString("SearchAmountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận phòng.
        /// </summary>
        public static string SearchDateCheckIn {
            get {
                return ResourceManager.GetString("SearchDateCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả phòng.
        /// </summary>
        public static string SearchDateCheckOut {
            get {
                return ResourceManager.GetString("SearchDateCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÁCH SẠN PHỔ BIẾN.
        /// </summary>
        public static string SearchLocationPopularHotel {
            get {
                return ResourceManager.GetString("SearchLocationPopularHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh / Thành phố.
        /// </summary>
        public static string SearchLocationProvinceAndCity {
            get {
                return ResourceManager.GetString("SearchLocationProvinceAndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
    }
}
